/* Copyright 2023 BD7PPWD
 * https://github.com/MaiLunjiye
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
 */

#ifndef FONT_ZH_CN_H
#define FONT_ZH_CN_H

#include <stdint.h>

typedef enum {
   ZH_CN_静,
   ZH_CN_噪,
   ZH_CN_等,
   ZH_CN_级,
   ZH_CN_步,
   ZH_CN_进,
   ZH_CN_频,
   ZH_CN_率,
   ZH_CN_宽,
   ZH_CN_窄,
   ZH_CN_带,
   ZH_CN_发,
   ZH_CN_射,
   ZH_CN_功,
   ZH_CN_高,
   ZH_CN_中,
   ZH_CN_低,
   ZH_CN_接,
   ZH_CN_收,
   ZH_CN_数,
   ZH_CN_字,
   ZH_CN_亚,
   ZH_CN_音,
   ZH_CN_模,
   ZH_CN_拟,
   ZH_CN_差,
   ZH_CN_方,
   ZH_CN_向,
   ZH_CN_超,
   ZH_CN_时,
   ZH_CN_秒,
   ZH_CN_分,
   ZH_CN_信,
   ZH_CN_道,
   ZH_CN_主,
   ZH_CN_上,
   ZH_CN_下,
   ZH_CN_双,
   ZH_CN_守,
   ZH_CN_开,
   ZH_CN_关,
   ZH_CN_加,
   ZH_CN_密,
   ZH_CN_遇,
   ZH_CN_忙,
   ZH_CN_禁,
   ZH_CN_保,
   ZH_CN_存,
   ZH_CN_修,
   ZH_CN_改,
   ZH_CN_名,
   ZH_CN_确,
   ZH_CN_认,
   ZH_CN_删,
   ZH_CN_除,
   ZH_CN_显,
   ZH_CN_示,
   ZH_CN_号,
   ZH_CN_省,
   ZH_CN_电,
   ZH_CN_式,
   ZH_CN_声,
   ZH_CN_控,
   ZH_CN_背,
   ZH_CN_光,
   ZH_CN_间,
   ZH_CN_亮,
   ZH_CN_起,
   ZH_CN_按,
   ZH_CN_键,
   ZH_CN_语,
   ZH_CN_文,
   ZH_CN_英,
   ZH_CN_扫,
   ZH_CN_描,
   ZH_CN_恢,
   ZH_CN_复,
   ZH_CN_结,
   ZH_CN_束,
   ZH_CN_终,
   ZH_CN_止,
   ZH_CN_盘,
   ZH_CN_锁,
   ZH_CN_入,
   ZH_CN_表,
   ZH_CN_尾,
   ZH_CN_消,
   ZH_CN_过,
   ZH_CN_继,
   ZH_CN_麦,
   ZH_CN_克,
   ZH_CN_风,
   ZH_CN_灵,
   ZH_CN_敏,
   ZH_CN_度,
   ZH_CN_量,
   ZH_CN_条,
   ZH_CN_压,
   ZH_CN_扩,
   ZH_CN_一,
   ZH_CN_即,
   ZH_CN_呼,
   ZH_CN_默,
   ZH_CN_查,
   ZH_CN_看,
   ZH_CN_告,
   ZH_CN_警,
   ZH_CN_本,
   ZH_CN_地,
   ZH_CN_远,
   ZH_CN_端,
   ZH_CN_身,
   ZH_CN_份,
   ZH_CN_码,
   ZH_CN_线,
   ZH_CN_始,
   ZH_CN_侧,
   ZH_CN_解,
   ZH_CN_响,
   ZH_CN_应,
   ZH_CN_铃,
   ZH_CN_回,
   ZH_CN_位,
   ZH_CN_预,
   ZH_CN_载,
   ZH_CN_波,
   ZH_CN_使,
   ZH_CN_能,
   ZH_CN_标,
   ZH_CN_志,
   ZH_CN_通,
   ZH_CN_讯,
   ZH_CN_录,
   ZH_CN_实,
   ZH_CN_屏,
   ZH_CN_息,
   ZH_CN_白,
   ZH_CN_黑,
   ZH_CN_嘟,
   ZH_CN_蛤,
   ZH_CN_调,
   ZH_CN_制,
   ZH_CN_短,
   ZH_CN_手,
   ZH_CN_监,
   ZH_CN_听,
   ZH_CN_紧,
   ZH_CN_急,
   ZH_CN_报,
   ZH_CN_机,
   ZH_CN_送,
   ZH_CN_长,
   ZH_CN_版,
   ZH_CN_留,
   ZH_CN_完,
   ZH_CN_全,
   ZH_CN_NUM,
} ZH_CN_Index;

// 12 x 12 bit
#define FONT_ZH_CN_WIDTH 12
#define FONT_ZH_CN_ARRAY_LEN 18

extern const uint8_t g_font_ZH_CN[ZH_CN_NUM][FONT_ZH_CN_ARRAY_LEN];

void UI_Display_ZH_CN(ZH_CN_Index ch, uint8_t x, uint8_t line);

#endif
